### PR TITLE
Fixes for https://github.com/ethereum/ethereum-org/issues/718

### PR DESCRIPTION
**Pull request by cleanforestco**

### CODE REVIEW

**Comment by cleanforestco** [comment]
NOTE: To enable the legal module so that it displays on the home page, add a class of "visible" to the .legal-modal DIV:

<div class="legal-modal visible">

**Comment by alexvandesande** [comment]
Are you sure it's a broken css? It seems to work fine for some people and not others, and it works locally..

**Comment by cleanforestco** [comment]
Hi @alexvandesande. Yes the website displays correctly for some users but not for others. I've seen people suggest the cause is network issues, cache issues, etc.

The answer is that the website displays correctly for those using Retina displays. The required CSS is wrapped in a Retina Display Media Query:
@media only screen and (-webkit-min-device-pixel-ratio: 2) { }

So users without Retina displays are not seeing the required CSS, leading to the display issues.

My PR should fix this.

**Comment by cleanforestco** [comment]
This issue is now fixed and can be closed.

**Pull request closed without merging**
