### PR TITLE
crowdsale typo fixes

### PR DESCRIPTION
**Pull request by hrldcpr**

### CODE REVIEW

**Comment by hrldcpr** [comment]
Also, btw, the box emoji 📦 doesn't seem to show up on the website, even though it looks fine in the markdown, so not sure how to fix that.

**Comment by alexvandesande** [comment]
Thanks for the correction. I believe the emoji doesn't appear due to your browser not supporting emojis, I can see it. We could replace it with an image, but I'm not sure it's worth the trouble.

**Comment by hrldcpr** [comment]
Strange, I'm using the latest version of Chrome (49) on a Mac, no idea why it doesn't show up! The encoding (UTF-8) seems to be correct, and I can see that emoji on other pages, and disabling the custom font CSS doesn't help. Oh well!

**Comment by alexvandesande** [comment]
Just checked and indeed I see it on safari but not on chrome. Maybe some
weird chrome support bug?

On Fri, Mar 11, 2016 at 3:29 PM, harold cooper <notifications@github.com>
wrote:

> Strange, I'm using the latest version of Chrome (49) on a Mac, no idea why
> it doesn't show up! The encoding (UTF-8) seems to be correct, and I can see
> that emoji on other pages, and disabling the custom font CSS doesn't help.
> Oh well!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/ethereum-org/pull/195#issuecomment-195489806>
> .
>



-- 

Alex Van de Sande
UX Designer

**Comment by alexvandesande** [comment]
In this github page I can see the emoji on both mac and chrome. I think I'll let it slide for now but will think on what might cause that.

These changes will be included on the next update, thanks for you contribution
https://github.com/ethereum/ethereum-org/pull/198

**Comment by hrldcpr** [comment]
Cool at least it's not just me. And yup, my pleasure, thanks for the interesting docs!

**Pull request merged**
