### PR TITLE
Image Updates and text tweaks

### PR DESCRIPTION
**Pull request by cleanforestco**
* Adding more vibrant photos.
* Add missing etherspace to, “…developed by theEthereum…”.
* H2 style updates: colour change, uppercase, letter-spacing.
* Change footer h3 colour.
* Replaced all text colour: #f2f2f2; with #fff.

All images from unsplash.com

screenshot 2017-10-27 02 17 40

Here is a short video comparing the old and new images:
https://www.dropbox.com/s/5j9ykiv1xajld5z/Ethereum.org%20Photos.mov?dl=1

### CODE REVIEW

**Comment by alexvandesande** [comment]
The main home image is indeed very beautiful, but I'm not sure what is the connection to Ethereum (well the current building connection is very subtle, I agree, it's just a geometric shape)

I'm not such a fan of the others thou, I think it reduces their readability and the cartoon + realistic photo is a weird contrast. 

I'd love to hear more opinions on this

**Comment by ryanio** [comment]
I agree that the current home hero has a nice reference to the diamond shaped logo, so changing it from that should require some reason or similar metaphor. The cascading mountain range is a nice picture though.

I'm not a big fan of the other stylistic updates, just from a personal design preference. For example, the reason to have #f2f2f2 instead of #fff (pure white) is due to contrast. This is a good reasoning here: https://graphicdesign.stackexchange.com/a/25360

**Comment by cleanforestco** [comment]
Hello @alexvandesande , 

I honestly never got the connection between the hero image shape and the ETH logo - I just thought it was a nice looking image. There are some visual similarities, but no deeper meaning I don't think. The cartoony pink/blue cloud images don't seem to have any specific connection to Ethereum. 

I do like the current main hero image, but the website has been using those same background images for over a year now. Time for a change I think! ;-)

Here is a short video comparing the old and new image:
https://www.dropbox.com/s/5j9ykiv1xajld5z/Ethereum.org%20Photos.mov?dl=1

The new photos are a bold change. The text contrast doesn't always work so things will have to be tweaked some more. But #721 is hopefully a good push to get some fresh images in place.

@ryanio agreed about #f2f2f2.

**Comment by Souptacular** [comment]
Thank you so much for your contributions. We are in the process of doing some major updates to the content and design of the site, with the help of a graphic designer from the EF. Please join us in our Gitter room (https://gitter.im/ethereum/ethereum-org-website) where we have a shared Google document and discussion around the changes that are being made. We love contributions/feedback.

**Pull request closed without merging**
