### PR TITLE
Updating links to wallet version 0.7.0 from 0.5.2

### PR DESCRIPTION
**Pull request by pascalvanhecke**

### CODE REVIEW

**Comment by alexvandesande** [comment]
Thanks for the PR, but I ended up adding a variable to make it easier to update it in the future

**Comment by bobsummerwill** [comment]
It might be better yet to just link to "latest".    I'm thinking that would be best for ethdocs.org too.

Keeping these specific version links up to date for both websites is mainly busy-work now.    When we are are AT Homestead, it was very important to point to specific versions.   Not so much now.

**Comment by alexvandesande** [comment]
I know, but here's my logic: 

I want to reduce confusion anywhere for most users, and reducing something from 3 clicks to 2 or even 1, does that, specially if the user doesn't need to fish around looking for the download link.

Doing direct links benefits thousands of users and the cost is me having to manually update the links once a week or so. I can do a few other things to make it even easier or automate it so it fetches the links automatically, but then I have to consider if [it's worth the time](https://xkcd.com/1205/).

Also, I link to "latest" below the button and when the user is not on a Mac, Win64 or Linux64.

**Comment by bobsummerwill** [comment]
Yes.   It probably is worth it, isn't it?
Just boring for **us** :-)

**Comment by alexvandesande** [comment]
I'll play a funny tune next time I do it, to make it more fun!

On Mon, Apr 18, 2016 at 6:37 PM, Bob Summerwill <notifications@github.com>
wrote:

> Yes. It probably is worth it, isn't it?
> Just boring for *us* :-)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/ethereum-org/pull/231#issuecomment-211593513>
>



-- 

Alex Van de Sande
UX Designer

**Pull request closed without merging**
