### PR TITLE
Upgrade Jade 1.9 to Pug 2.0

### PR DESCRIPTION
**Pull request by ryanio**
Jade was renamed to Pug due to a [trademark issue](https://pugjs.org/api/migration-v2.html#project-rename), and Pug 2 was released Aug 2016.

This PR upgrades everything from Jade to Pug and fixes any breaking changes.

### CODE REVIEW

**Comment by alexvandesande** [comment]
This has been fixed and merged at https://github.com/ethereum/ethereum-org/pull/670

Thanks for your contributions Ryan!

**Comment by ryanio** [comment]
No problem! :)

**Comment by alexvandesande** [comment]
I'm actually reopening it: upon further testing I had an error on internal pages and reverted the changes.

I would still welcome if you could take a second look on your PR - or if I need to fix something in my side to fix it.

**Comment by ryanio** [comment]
Hm it's working for me. What is the error?

Did you restart your dev server after bringing in the changes? Because there's a changed line in app.js to use pug instead of jade files (https://github.com/ethereum/ethereum-org/pull/669/commits/e3a824d781636e569acd2653ce8872247a086aca)

**Comment by alexvandesande** [comment]
You're correct. it works now!

**Comment by ryanio** [comment]
Great!

**Pull request closed without merging**
