### PR TITLE
Rebuilt the presale ether checker to use the actual genesis

### PR DESCRIPTION
**Pull request by holiman**
It now uses the actual Ethereum genesis. This PR does not include the actual rebuild - I'm not sure if there are any specialities when deploying this. @alexvandesande PTAL ?

### CODE REVIEW

**Comment by Souptacular** [comment]
@alexvandesande would know about this more than I would. What was it pulling from before?

**Comment by holiman** [comment]
>  What was it pulling from before?

https://github.com/ethereum/ethereum-org/pull/601/files#diff-6948e493a94a16fa48a02f4d4db4c34fL1

I thought you @Souptacular had some involvement in the website, but maybe @jpitts can give a :+1: or :-1:  on this also?

**Comment by Souptacular** [comment]
@holiman. That specific part of the site pre-dated James or I being on the team. @alexvandesande was around when it was set-up I believe.

**Comment by alexvandesande** [comment]
Thanks @holiman ! Can you please make this PR against master and I'll build it into gh-pages?

**Pull request closed without merging**
