### PR TITLE
Replace myToken with MyToken

### PR DESCRIPTION
**Pull request by makoto**
The contract name is called `MyToken` though some of constructor functions are referred as `myToken` hence they were not recognised as constructors

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Hey, @makoto!   Thanks for that.   Looks like other changes were made to this file, and you'll need to merge/resolve the conflicts before your fixes can be merged.

**Comment by bobsummerwill** [comment]
Hey @makoto!

It looks like this issue has been addressed by this - https://github.com/ethereum/ethereum-org/pull/220/files, so I think this PR is now obsolete.

Please could you double-check?      Thanks for submitting it, and we welcome further fixes.   The more eyes the better.

Please do also check out http://github.com/ethereum/homestead-guide (and http://ethdocs.org).   We could really use exact help there :-)

**Comment by makoto** [comment]
Hi @bobsummerwill . I will look into homestead guide once you merge its existing pull requests (I actually spotted one error there, created PR, then noticed somone else already spotted in the unmerged PR).

With regards to the token tutorial, I would suggest simplifying a lot as they are very complex. I also noticed that any `proof of work` related codes (eg: `giveBlockReward`) are not even in the Full coin code, and I have no idea how I can execute these functions. I will be recording the walk through of the tutorial and also write down some findings while doing the tutorial at https://medium.com/@makoto_inoue Hope my insight can help improving the docs.

**Comment by makoto** [comment]
@bobsummerwill  With regards to open PRs,  I meant for https://github.com/ethereum/homestead-guide/pulls which had 3 open PR but now looks like you closed most of them so I will have a look. With regards to token tutorial, I recorded in the videos how I completed and posted into a series of articles at https://medium.com/@makoto_inoue . It was meant for walk through to new people but ended up having more questions than answers. Would be great if you can take a look and answer my questions when you have time. 

Cheers.

Makoto

**Pull request closed without merging**
