### PR TITLE
Updating broken links

### PR DESCRIPTION
**Pull request by BartoszNow**
Fixed link to "What is ether?", removed non-existent "The Ethereum Ecossystem"

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Hey @BartoszNow!
Thanks for the PR, but it looks like we can do better again :-)

Rather than http://ethereum-homestead.readthedocs.org/en/latest/ether.html, we should actually link to http://ethdocs.org/en/latest/ether.html.   We got a "pretty URL" after these links were original setup.

Perhaps you could do a sweep on all ethereum-homestead.readthedocs.org links and we can fix them all right now, while we remember?    Want to add a second commit to this PR to do that?   Would be much appreciated.   Thanks!

**Comment by BartoszNow** [comment]
Thanks @bobsummerwill for reviewing, I've updated the Ether link.

With this PR I want to fix a bug - broken links. I'd imagine that's P1 issue, while changes you've suggested are improvements of working code, so P3 probably. I simply don't have a bandwidth for any P3s right now.
So how about merging this PR now and creating a story/task in whatever tasking system you guys use for link improvements?

**Comment by bobsummerwill** [comment]
Will do - thanks for the fix!
@alexvandesande Looks like I don't have Merge rights.   Would you like to grant me such?   If not, you'll have to do the merge here!

**Comment by alexvandesande** [comment]
@bobsummerwill I gave you merge rights. But I'll handle this PR

**Comment by bobsummerwill** [comment]
Thanks, @alexvandesande!

Just to be clear ... I'm not planning on merging much, but if I can help move things along (reviews, merges for non-scary fixes, etc), I'm happy to help.

**Pull request merged**
